version: '3.3'

services:
  web:
    build: .
    command: gunicorn fl_web_app.wsgi:application --bind 0.0.0.0:8080
    volumes:
      - .:/app
    expose:
      - "8080"
    env_file:
      - .env
    networks:
      - fl_web_app_my_docker_network
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - fl_web_app_my_docker_network
    restart: always

networks:
  fl_web_app_my_docker_network:
    external: true
