version: '3.3'

services:
  web:
    build: .
    command: gunicorn fl_web_app.wsgi:application --bind 0.0.0.0:8080
    volumes:
      - .:/app
    expose:
      - 8080
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
