# Generated by Django 4.2.16 on 2024-09-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DettaglioSkPressa",
            fields=[
                (
                    "id_dettaglio_sk_pressa",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "programma_pressa",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("riservato", models.CharField(blank=True, max_length=255, null=True)),
                ("pressione_stiratura", models.IntegerField(blank=True, null=True)),
                ("tempo_stiratura", models.IntegerField(blank=True, null=True)),
                ("pressione_placcatura", models.IntegerField(blank=True, null=True)),
                (
                    "doppia_stiratura_pressione1",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "doppia_stiratura_pressione2",
                    models.IntegerField(blank=True, null=True),
                ),
                ("doppia_stiratura_tempo1", models.IntegerField(blank=True, null=True)),
                ("doppia_stiratura_tempo2", models.IntegerField(blank=True, null=True)),
                (
                    "tripla_stiratura_pressione1",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "tripla_stiratura_pressione2",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "tripla_stiratura_pressione3",
                    models.IntegerField(blank=True, null=True),
                ),
                ("tripla_stiratura_tempo1", models.IntegerField(blank=True, null=True)),
                ("tripla_stiratura_tempo2", models.IntegerField(blank=True, null=True)),
                ("tripla_stiratura_tempo3", models.IntegerField(blank=True, null=True)),
                (
                    "battute_multiple_pressione_chiusura",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "battute_multiple_pressione_inferiore",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "battute_multiple_pressione_successive",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "tempo_chiusura_battute_multiple",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "tempi_successivi_battute_multiple",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "numero_chiusure_battute_multiple",
                    models.IntegerField(blank=True, null=True),
                ),
                ("temperatura1", models.IntegerField(blank=True, null=True)),
                ("temperatura2", models.IntegerField(blank=True, null=True)),
                ("temperatura3", models.IntegerField(blank=True, null=True)),
                ("temperatura4", models.IntegerField(blank=True, null=True)),
                ("temperatura5", models.IntegerField(blank=True, null=True)),
                ("temperatura6", models.IntegerField(blank=True, null=True)),
                ("temperatura7", models.IntegerField(blank=True, null=True)),
                ("temperatura8", models.IntegerField(blank=True, null=True)),
                ("temperatura9", models.IntegerField(blank=True, null=True)),
                ("temperatura10", models.IntegerField(blank=True, null=True)),
                ("temperatura11", models.IntegerField(blank=True, null=True)),
                ("temperatura12", models.IntegerField(blank=True, null=True)),
                ("temperatura13", models.IntegerField(blank=True, null=True)),
                ("temperatura14", models.IntegerField(blank=True, null=True)),
                ("temperatura15", models.IntegerField(blank=True, null=True)),
                ("temperatura16", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "dettaglio_sk_pressa",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ImpostazionePressa",
            fields=[
                (
                    "id_impostazione",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "programma_pressa",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("riservato", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "pressione_stiratura",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "tempo_stiratura",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "pressione_placcatura",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "doppia_stiratura_pressione1",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "doppia_stiratura_pressione2",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "doppia_stiratura_tempo1",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "doppia_stiratura_tempo2",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "tripla_stiratura_pressione1",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "tripla_stiratura_pressione2",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "tripla_stiratura_pressione3",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "tripla_stiratura_tempo1",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "tripla_stiratura_tempo2",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "tripla_stiratura_tempo3",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "battute_multiple_pressione_chiusura",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "battute_multiple_pressione_inferiore",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "battute_multiple_pressione_successive",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "tempo_chiusura_battute_multiple",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "tempi_successivi_battute_multiple",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "numero_chiusure_battute_multiple",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "temperatura1",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "temperatura2",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "temperatura3",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "temperatura4",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "temperatura5",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "temperatura6",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "temperatura7",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "temperatura8",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "temperatura9",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "temperatura10",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "temperatura11",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "temperatura12",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "temperatura13",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "temperatura14",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "temperatura15",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "temperatura16",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                ("created_at", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "impostazione_pressa",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProgrammaPressa",
            fields=[
                (
                    "id_programma_pressa",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "descrizione",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "programma_pressa",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Ricetta",
            fields=[
                ("id_ricetta", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "db_table": "ricetta",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RiscontroPressa",
            fields=[
                ("id_riscontro", models.AutoField(primary_key=True, serialize=False)),
                ("id_scheda", models.IntegerField(blank=True, null=True)),
                ("data_inizio", models.DateTimeField(blank=True, null=True)),
                ("ora_inizio", models.DateTimeField(blank=True, null=True)),
                ("data_fine", models.DateTimeField(blank=True, null=True)),
                ("ora_fine", models.DateTimeField(blank=True, null=True)),
                ("numero_pelli", models.IntegerField(blank=True, null=True)),
                (
                    "programma_pressa",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("pressione_stiratura", models.IntegerField(blank=True, null=True)),
                ("tempo_stiratura", models.IntegerField(blank=True, null=True)),
                ("pressione_placcatura", models.IntegerField(blank=True, null=True)),
                (
                    "doppia_stiratura_pressione1",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "doppia_stiratura_pressione2",
                    models.IntegerField(blank=True, null=True),
                ),
                ("doppia_stiratura_tempo1", models.IntegerField(blank=True, null=True)),
                ("doppia_stiratura_tempo2", models.IntegerField(blank=True, null=True)),
                (
                    "tripla_stiratura_pressione1",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "tripla_stiratura_pressione2",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "tripla_stiratura_pressione3",
                    models.IntegerField(blank=True, null=True),
                ),
                ("tripla_stiratura_tempo1", models.IntegerField(blank=True, null=True)),
                ("tripla_stiratura_tempo2", models.IntegerField(blank=True, null=True)),
                ("tripla_stiratura_tempo3", models.IntegerField(blank=True, null=True)),
                (
                    "battute_multiple_pressione_chiusura",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "battute_multiple_pressione_inferiore",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "battute_multiple_pressione_successive",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "tempo_chiusura_battute_multiple",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "tempi_successivi_battute_multiple",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "numero_chiusure_battute_multiple",
                    models.IntegerField(blank=True, null=True),
                ),
                ("temperatura1", models.IntegerField(blank=True, null=True)),
                ("temperatura2", models.IntegerField(blank=True, null=True)),
                ("temperatura3", models.IntegerField(blank=True, null=True)),
                ("tempant", models.IntegerField(blank=True, null=True)),
                ("temppost", models.IntegerField(blank=True, null=True)),
                ("temperatura4", models.IntegerField(blank=True, null=True)),
                ("temperatura5", models.IntegerField(blank=True, null=True)),
                ("temperatura6", models.IntegerField(blank=True, null=True)),
                ("temperatura7", models.IntegerField(blank=True, null=True)),
                ("temperatura8", models.IntegerField(blank=True, null=True)),
                ("temperatura9", models.IntegerField(blank=True, null=True)),
                ("temperatura10", models.IntegerField(blank=True, null=True)),
                ("temperatura11", models.IntegerField(blank=True, null=True)),
                ("temperatura12", models.IntegerField(blank=True, null=True)),
                ("temperatura13", models.IntegerField(blank=True, null=True)),
                ("temperatura14", models.IntegerField(blank=True, null=True)),
                ("temperatura15", models.IntegerField(blank=True, null=True)),
                ("temperatura16", models.IntegerField(blank=True, null=True)),
                ("tensione_fase1", models.IntegerField(blank=True, null=True)),
                ("tensione_fase2", models.IntegerField(blank=True, null=True)),
                ("tensione_fase3", models.IntegerField(blank=True, null=True)),
                ("corrente_fase1", models.IntegerField(blank=True, null=True)),
                ("corrente_fase2", models.IntegerField(blank=True, null=True)),
                ("corrente_fase3", models.IntegerField(blank=True, null=True)),
                ("potenza_attiva", models.IntegerField(blank=True, null=True)),
                ("potenza_reattiva", models.IntegerField(blank=True, null=True)),
                (
                    "contatore_energia_attiva",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "contatore_energia_reattiva",
                    models.IntegerField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "riscontro_pressa",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SchedaLavorazione",
            fields=[
                ("id_scheda", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateField(auto_now_add=True, null=True)),
                ("rif_ddt", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "scheda_lavorazione",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblazienda",
            fields=[
                (
                    "idragsoc",
                    models.AutoField(
                        db_column="IDRagSoc", primary_key=True, serialize=False
                    ),
                ),
                (
                    "ragionesociale",
                    models.CharField(
                        blank=True, db_column="RagioneSociale", max_length=50, null=True
                    ),
                ),
                (
                    "indirizzo",
                    models.CharField(
                        blank=True, db_column="Indirizzo", max_length=50, null=True
                    ),
                ),
                (
                    "cap",
                    models.CharField(
                        blank=True, db_column="CAP", max_length=50, null=True
                    ),
                ),
                (
                    "comune",
                    models.CharField(
                        blank=True, db_column="Comune", max_length=50, null=True
                    ),
                ),
                (
                    "provincia",
                    models.CharField(
                        blank=True, db_column="Provincia", max_length=50, null=True
                    ),
                ),
                (
                    "partitaiva",
                    models.CharField(
                        blank=True, db_column="PartitaIVA", max_length=50, null=True
                    ),
                ),
                (
                    "ufficio",
                    models.CharField(
                        blank=True, db_column="Ufficio", max_length=50, null=True
                    ),
                ),
            ],
            options={
                "db_table": "tblAzienda",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblclienti",
            fields=[
                (
                    "idcliente",
                    models.AutoField(
                        db_column="IDCliente", primary_key=True, serialize=False
                    ),
                ),
                (
                    "ragionesociale",
                    models.CharField(
                        blank=True,
                        db_column="RagioneSociale",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "indirizzo",
                    models.CharField(
                        blank=True, db_column="Indirizzo", max_length=100, null=True
                    ),
                ),
                (
                    "cap",
                    models.CharField(
                        blank=True, db_column="CAP", max_length=50, null=True
                    ),
                ),
                (
                    "città",
                    models.CharField(
                        blank=True, db_column="Città", max_length=50, null=True
                    ),
                ),
                (
                    "provincia",
                    models.CharField(
                        blank=True, db_column="Provincia", max_length=50, null=True
                    ),
                ),
                (
                    "piva",
                    models.CharField(
                        blank=True, db_column="PIVA", max_length=50, null=True
                    ),
                ),
                (
                    "tel",
                    models.CharField(
                        blank=True, db_column="Tel", max_length=50, null=True
                    ),
                ),
                (
                    "fax",
                    models.CharField(
                        blank=True, db_column="FAX", max_length=50, null=True
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, db_column="Email", max_length=50, null=True
                    ),
                ),
                (
                    "cf",
                    models.CharField(
                        blank=True, db_column="CF", max_length=255, null=True
                    ),
                ),
                (
                    "ufficioiva",
                    models.CharField(
                        blank=True, db_column="UfficioIVA", max_length=255, null=True
                    ),
                ),
                (
                    "idpagamento",
                    models.IntegerField(blank=True, db_column="IDPagamento", null=True),
                ),
                (
                    "idiva",
                    models.IntegerField(blank=True, db_column="IDIVA", null=True),
                ),
                (
                    "idbanca",
                    models.IntegerField(blank=True, db_column="IDBanca", null=True),
                ),
                (
                    "agenzia",
                    models.CharField(
                        blank=True, db_column="Agenzia", max_length=255, null=True
                    ),
                ),
                (
                    "iban",
                    models.CharField(
                        blank=True, db_column="IBAN", max_length=255, null=True
                    ),
                ),
                (
                    "nascondi",
                    models.BooleanField(blank=True, db_column="Nascondi", null=True),
                ),
                ("idum", models.IntegerField(blank=True, db_column="IDUM", null=True)),
            ],
            options={
                "db_table": "tblClienti",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblcolori",
            fields=[
                (
                    "idcolore",
                    models.AutoField(
                        db_column="IDColore", primary_key=True, serialize=False
                    ),
                ),
                (
                    "colore",
                    models.CharField(
                        blank=True,
                        db_column="Colore",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
            options={
                "db_table": "tblColori",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblddtingresso",
            fields=[
                (
                    "idddtingresso",
                    models.AutoField(
                        db_column="IDDDTIngresso", primary_key=True, serialize=False
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True, db_column="Numero", max_length=255, null=True
                    ),
                ),
                ("data", models.DateTimeField(blank=True, db_column="Data", null=True)),
                ("note", models.TextField(blank=True, db_column="Note", null=True)),
                (
                    "noteindettaglio",
                    models.BooleanField(
                        blank=True, db_column="NoteInDettaglio", null=True
                    ),
                ),
            ],
            options={
                "db_table": "tblDDTIngresso",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblddtuscita",
            fields=[
                (
                    "idddtuscita",
                    models.AutoField(
                        db_column="IDDDTUscita", primary_key=True, serialize=False
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True, db_column="Numero", max_length=255, null=True
                    ),
                ),
                ("data", models.DateTimeField(blank=True, db_column="Data", null=True)),
            ],
            options={
                "db_table": "tblDDTUscita",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tbldettddtingresso",
            fields=[
                (
                    "iddettddtingresso",
                    models.AutoField(
                        db_column="IDDettDDTIngresso", primary_key=True, serialize=False
                    ),
                ),
                (
                    "idddtingresso",
                    models.IntegerField(
                        blank=True, db_column="IDDDTIngresso", null=True
                    ),
                ),
                (
                    "idgruppo",
                    models.IntegerField(blank=True, db_column="IDGruppo", null=True),
                ),
                (
                    "idtaglia",
                    models.IntegerField(blank=True, db_column="IDTaglia", null=True),
                ),
                (
                    "idtipostampa",
                    models.IntegerField(
                        blank=True, db_column="IDTipoStampa", null=True
                    ),
                ),
                (
                    "idfase",
                    models.IntegerField(blank=True, db_column="IDFase", null=True),
                ),
                ("idum", models.IntegerField(blank=True, db_column="IDUM", null=True)),
                (
                    "quantita",
                    models.DecimalField(
                        blank=True,
                        db_column="Quantita",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "consegna",
                    models.CharField(
                        blank=True, db_column="Consegna", max_length=255, null=True
                    ),
                ),
                (
                    "evaso",
                    models.BooleanField(blank=True, db_column="Evaso", null=True),
                ),
                ("note", models.TextField(blank=True, db_column="Note", null=True)),
                (
                    "idcolore",
                    models.IntegerField(blank=True, db_column="IDColore", null=True),
                ),
                (
                    "notedamacchina",
                    models.TextField(blank=True, db_column="NoteDaMacchina", null=True),
                ),
                (
                    "idimpeff",
                    models.IntegerField(blank=True, db_column="IDImpEff", null=True),
                ),
                (
                    "idimpmacchina",
                    models.IntegerField(
                        blank=True, db_column="IDImpMacchina", null=True
                    ),
                ),
            ],
            options={
                "db_table": "tblDettDDTIngresso",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tbldettddtuscita",
            fields=[
                (
                    "iddettddtuscita",
                    models.AutoField(
                        db_column="IDDettDDTUscita", primary_key=True, serialize=False
                    ),
                ),
                (
                    "idddtuscita",
                    models.IntegerField(blank=True, db_column="IDDDTUscita", null=True),
                ),
                (
                    "idgruppo",
                    models.IntegerField(blank=True, db_column="IDGruppo", null=True),
                ),
                (
                    "um",
                    models.CharField(
                        blank=True, db_column="UM", max_length=2, null=True
                    ),
                ),
                (
                    "quantita",
                    models.DecimalField(
                        blank=True,
                        db_column="Quantita",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "tblDettDDTUscita",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tbldettmacchine",
            fields=[
                (
                    "iddettmacchine",
                    models.AutoField(
                        db_column="IDDettMacchine", primary_key=True, serialize=False
                    ),
                ),
                (
                    "idmacchina",
                    models.IntegerField(blank=True, db_column="IDMacchina", null=True),
                ),
                (
                    "iddettddtingresso",
                    models.IntegerField(
                        blank=True, db_column="IDDettDDTIngresso", null=True
                    ),
                ),
                (
                    "quantita",
                    models.DecimalField(
                        blank=True,
                        db_column="Quantita",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "datainizio",
                    models.DateTimeField(blank=True, db_column="DataInizio", null=True),
                ),
            ],
            options={
                "db_table": "tblDettMacchine",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblfasi",
            fields=[
                (
                    "idfase",
                    models.AutoField(
                        db_column="IDFase", primary_key=True, serialize=False
                    ),
                ),
                (
                    "fase",
                    models.CharField(
                        blank=True, db_column="Fase", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "tblFasi",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblgruppi",
            fields=[
                (
                    "idgruppo",
                    models.AutoField(
                        db_column="IDGruppo", primary_key=True, serialize=False
                    ),
                ),
                (
                    "descrizione",
                    models.CharField(
                        blank=True, db_column="Descrizione", max_length=255, null=True
                    ),
                ),
                (
                    "codice",
                    models.CharField(
                        blank=True, db_column="Codice", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "tblGruppi",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblimpeff",
            fields=[
                (
                    "idimpeff",
                    models.AutoField(
                        db_column="IDImpEff", primary_key=True, serialize=False
                    ),
                ),
                (
                    "idddtingresso",
                    models.IntegerField(
                        blank=True, db_column="IDDDTIngresso", null=True
                    ),
                ),
                (
                    "iddettddtingresso",
                    models.IntegerField(
                        blank=True, db_column="IDDettDDTIngresso", null=True
                    ),
                ),
                (
                    "idcliente",
                    models.IntegerField(blank=True, db_column="IDCliente", null=True),
                ),
                (
                    "idmacchina",
                    models.IntegerField(blank=True, db_column="IDMacchina", null=True),
                ),
                (
                    "idtipostampa",
                    models.IntegerField(
                        blank=True, db_column="IDTipoStampa", null=True
                    ),
                ),
                (
                    "idgruppo",
                    models.IntegerField(blank=True, db_column="IDGruppo", null=True),
                ),
                (
                    "idfase",
                    models.IntegerField(blank=True, db_column="IDFase", null=True),
                ),
                (
                    "pressione",
                    models.DecimalField(
                        blank=True,
                        db_column="Pressione",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "temperatura",
                    models.DecimalField(
                        blank=True,
                        db_column="Temperatura",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "tempo",
                    models.CharField(
                        blank=True, db_column="Tempo", max_length=255, null=True
                    ),
                ),
                (
                    "idmateriale",
                    models.IntegerField(blank=True, db_column="IDMateriale", null=True),
                ),
                (
                    "idmatinlavoro",
                    models.IntegerField(
                        blank=True, db_column="IDMatInLavoro", null=True
                    ),
                ),
                (
                    "idcolore",
                    models.IntegerField(blank=True, db_column="IDColore", null=True),
                ),
            ],
            options={
                "db_table": "tblImpEff",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblimpmacchina",
            fields=[
                (
                    "idimpmacchina",
                    models.AutoField(
                        db_column="IDImpMacchina", primary_key=True, serialize=False
                    ),
                ),
                (
                    "idcliente",
                    models.IntegerField(blank=True, db_column="IDCliente", null=True),
                ),
                (
                    "idmacchina",
                    models.IntegerField(blank=True, db_column="IDMacchina", null=True),
                ),
                (
                    "idtipostampa",
                    models.IntegerField(
                        blank=True, db_column="IDTipoStampa", null=True
                    ),
                ),
                (
                    "idgruppo",
                    models.IntegerField(blank=True, db_column="IDGruppo", null=True),
                ),
                (
                    "idfase",
                    models.IntegerField(blank=True, db_column="IDFase", null=True),
                ),
                (
                    "pressione",
                    models.DecimalField(
                        blank=True,
                        db_column="Pressione",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "temperatura",
                    models.DecimalField(
                        blank=True,
                        db_column="Temperatura",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "tempo",
                    models.CharField(
                        blank=True, db_column="Tempo", max_length=255, null=True
                    ),
                ),
                (
                    "idmateriale",
                    models.IntegerField(blank=True, db_column="IDMateriale", null=True),
                ),
                (
                    "idcolore",
                    models.IntegerField(blank=True, db_column="IDColore", null=True),
                ),
            ],
            options={
                "db_table": "tblImpMacchina",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblmacchine",
            fields=[
                (
                    "idmacchina",
                    models.AutoField(
                        db_column="IDMacchina", primary_key=True, serialize=False
                    ),
                ),
                (
                    "descrizione",
                    models.CharField(
                        blank=True, db_column="Descrizione", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "tblMacchine",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblmateriali",
            fields=[
                (
                    "idmateriale",
                    models.AutoField(
                        db_column="IDMateriale", primary_key=True, serialize=False
                    ),
                ),
                (
                    "materiale",
                    models.CharField(
                        blank=True, db_column="Materiale", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "tblMateriali",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblmatinlavoro",
            fields=[
                (
                    "idmatinlavoro",
                    models.AutoField(
                        db_column="IDMatInLavoro", primary_key=True, serialize=False
                    ),
                ),
                (
                    "iddettddtingresso",
                    models.IntegerField(
                        blank=True, db_column="IDDettDDTIngresso", null=True
                    ),
                ),
                (
                    "idmacchina",
                    models.IntegerField(blank=True, db_column="IDMacchina", null=True),
                ),
                (
                    "quantita",
                    models.DecimalField(
                        blank=True,
                        db_column="Quantita",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "lavorato",
                    models.BooleanField(blank=True, db_column="Lavorato", null=True),
                ),
                (
                    "priorità",
                    models.IntegerField(blank=True, db_column="Priorità", null=True),
                ),
                (
                    "idimpeff",
                    models.IntegerField(blank=True, db_column="IDImpEff", null=True),
                ),
                (
                    "idimpmacchina",
                    models.IntegerField(
                        blank=True, db_column="IDImpMacchina", null=True
                    ),
                ),
            ],
            options={
                "db_table": "tblMatInLavoro",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TblPercorso",
            fields=[
                (
                    "percorso_db",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "tbl_Percorso",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblstoccaggio",
            fields=[
                (
                    "idstoccaggio",
                    models.AutoField(
                        db_column="IDStoccaggio", primary_key=True, serialize=False
                    ),
                ),
                (
                    "iddettddtingresso",
                    models.IntegerField(
                        blank=True, db_column="IDDettDDTIngresso", null=True
                    ),
                ),
                (
                    "idzonamagazzino",
                    models.IntegerField(
                        blank=True, db_column="IDZonaMagazzino", null=True
                    ),
                ),
                (
                    "quantita",
                    models.DecimalField(
                        blank=True,
                        db_column="Quantita",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "lavorato",
                    models.BooleanField(blank=True, db_column="Lavorato", null=True),
                ),
                (
                    "inlavorazione",
                    models.BooleanField(
                        blank=True, db_column="InLavorazione", null=True
                    ),
                ),
            ],
            options={
                "db_table": "tblStoccaggio",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tbltaglie",
            fields=[
                (
                    "idtaglia",
                    models.AutoField(
                        db_column="IDTaglia", primary_key=True, serialize=False
                    ),
                ),
                (
                    "taglia",
                    models.CharField(
                        blank=True, db_column="Taglia", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "tblTaglie",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tbltipistampe",
            fields=[
                (
                    "idtipostampa",
                    models.AutoField(
                        db_column="IDTipoStampa", primary_key=True, serialize=False
                    ),
                ),
                (
                    "tipostampa",
                    models.CharField(
                        blank=True, db_column="TipoStampa", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "tblTipiStampe",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblum",
            fields=[
                (
                    "idum",
                    models.AutoField(
                        db_column="IDUM", primary_key=True, serialize=False
                    ),
                ),
                (
                    "um",
                    models.CharField(
                        blank=True, db_column="UM", max_length=2, null=True
                    ),
                ),
            ],
            options={
                "db_table": "tblUM",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tblzonemagazzino",
            fields=[
                (
                    "idzonamagazzino",
                    models.AutoField(
                        db_column="IDZonaMagazzino", primary_key=True, serialize=False
                    ),
                ),
                (
                    "zonamagazzino",
                    models.CharField(
                        blank=True, db_column="ZonaMagazzino", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "tblZoneMagazzino",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TFormatocolonne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nomemaschera",
                    models.CharField(
                        blank=True, db_column="NomeMaschera", max_length=100, null=True
                    ),
                ),
                (
                    "nomesottomaschera",
                    models.CharField(
                        blank=True,
                        db_column="NomeSottoMaschera",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "nomecolonna",
                    models.CharField(
                        blank=True, db_column="NomeColonna", max_length=100, null=True
                    ),
                ),
                (
                    "ordinecolonna",
                    models.IntegerField(
                        blank=True, db_column="OrdineColonna", null=True
                    ),
                ),
                (
                    "larghezzacolonna",
                    models.IntegerField(
                        blank=True, db_column="LarghezzaColonna", null=True
                    ),
                ),
            ],
            options={
                "db_table": "T_FormatoColonne",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TipoMacchina",
            fields=[
                (
                    "id_tipo_macchina",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "tipo_macchina",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "tipo_macchina",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TRicerca",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "nome",
                    models.CharField(
                        blank=True, db_column="Nome", max_length=50, null=True
                    ),
                ),
                (
                    "chiave",
                    models.CharField(
                        blank=True, db_column="Chiave", max_length=50, null=True
                    ),
                ),
                (
                    "tipochiavetesto",
                    models.BooleanField(
                        blank=True, db_column="TipoChiaveTesto", null=True
                    ),
                ),
                ("strsql", models.TextField(blank=True, db_column="strSQL", null=True)),
                (
                    "ordinamento",
                    models.CharField(
                        blank=True, db_column="Ordinamento", max_length=50, null=True
                    ),
                ),
                (
                    "ordinamento2",
                    models.CharField(
                        blank=True, db_column="Ordinamento2", max_length=50, null=True
                    ),
                ),
                (
                    "campi",
                    models.CharField(
                        blank=True, db_column="Campi", max_length=50, null=True
                    ),
                ),
                (
                    "colonne",
                    models.IntegerField(blank=True, db_column="Colonne", null=True),
                ),
                (
                    "larghezza",
                    models.CharField(
                        blank=True, db_column="Larghezza", max_length=100, null=True
                    ),
                ),
                (
                    "predefinito",
                    models.CharField(
                        blank=True, db_column="Predefinito", max_length=50, null=True
                    ),
                ),
                (
                    "originecombo",
                    models.CharField(
                        blank=True, db_column="OrigineCombo", max_length=50, null=True
                    ),
                ),
                (
                    "dacompilare",
                    models.CharField(
                        blank=True, db_column="DaCompilare", max_length=255, null=True
                    ),
                ),
                (
                    "vaiarecord",
                    models.BooleanField(blank=True, db_column="VaiaRecord", null=True),
                ),
                (
                    "formriferimento",
                    models.CharField(
                        blank=True,
                        db_column="FormRiferimento",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "mionome",
                    models.CharField(
                        blank=True, db_column="MioNome", max_length=50, null=True
                    ),
                ),
                (
                    "focus",
                    models.CharField(
                        blank=True, db_column="Focus", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "T_Ricerca",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Utenti",
            fields=[
                (
                    "idutente",
                    models.AutoField(
                        db_column="IDUtente", primary_key=True, serialize=False
                    ),
                ),
                (
                    "nomecomputer",
                    models.CharField(
                        blank=True, db_column="NomeComputer", max_length=50, null=True
                    ),
                ),
                (
                    "utente",
                    models.CharField(
                        blank=True, db_column="Utente", max_length=50, null=True
                    ),
                ),
                (
                    "percorsotabelle",
                    models.CharField(
                        blank=True,
                        db_column="PercorsoTabelle",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "percorsifilebackup",
                    models.CharField(
                        blank=True,
                        db_column="PercorsiFileBackup",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "Utenti",
                "managed": False,
            },
        ),
    ]
